var App=angular.module('app',['ng','ngRoute']);
// 跳转链接设置
    App.config(function($routeProvider){
        $routeProvider
        .when('/nav1',{
            templateUrl:'template/1.html',
            controller:'one'
        })
        .when('/nav2',{
            templateUrl:'template/2.html',
            controller:'two'
        })
        .when('/nav3',{
            templateUrl:'template/3.html',
            controller:'three'
        })
        .when('/nav4',{
            templateUrl:'template/4.html',
            controller:'four'
        })
        .when('/nav5',{
            templateUrl:'template/login.html',
            controller:'login'
        })
        .otherwise('/nav1');
    });
// 首页li链接高亮
    App.controller('headerCon',['$scope',     
        function($scope){
            $scope.arr=['首页','产品展示','新闻动态','留言板','登录/注册'];
            $scope.i=1;
            $scope.navs=function(index){
                $scope.i=(index+1);
            };
    }]);
// 第一个页面
    App.controller('one',['$scope','$interval',
        function($scope,$interval){
        $scope.arr=[1,2,3,4];
        $scope.i=1;
        let oBanner=document.getElementById("banner");
        oBanner.onmouseover=function(){
            $interval.cancel(timer);
        }
        oBanner.onmouseout=function(){
            timer=$interval($scope.lun,2000);
        }
        $scope.yuan=function(index){
            $scope.i=(index+1);
        }        
        $scope.ji=function(num){
            if(num==1){
                $scope.i--;
            }
            if($scope.i==0){
                $scope.i=4;
            }
            if(num==2){
                $scope.i++;
            }
            if($scope.i>4){
                $scope.i=1;
            }
        };
        $scope.lun=function(){
            $scope.i++;
            if($scope.i>4){
                $scope.i=1;
            }
        }    
        let timer=$interval($scope.lun,2000);
        
    }]);
// 第二个页面
    App.controller('two',['$scope',
        function($scope){
            $scope.arr=['意大利红酒','美国红酒','澳大利亚红酒','香槟酒','白葡萄酒','红葡萄酒','托斯卡纳','法国红酒'];
            $scope.photo=[
                {img:'2-1',text:"百加得"},
                {img:'2-2',text:"百加得黑朗姆酒"},
                {img:'2-3',text:"窗外风景干红葡萄酒"},
                {img:'2-4',text:"德保利精选霞多丽白葡萄酒"},
                {img:'2-5',text:"滴金庄(迪甘甜酒王白葡萄酒)"},
                {img:'2-6',text:"菲丽宝娜-皇家珍藏香槟"},
                {img:'2-7',text:"枫丹甘露（梦雪真）白葡萄酒"},
                {img:'2-8',text:"花悦干白葡萄酒"},
                {img:'2-9',text:"花悦红葡萄酒"},
                {img:'2-10',text:"罗斯福缘山白仙粉黛桃红葡萄酒"},
                {img:'2-11',text:"马琳娜博尔黑牌颂维翁"},
                {img:'2-12',text:"酩悦香槟(MOET&CHANDON)"},             
            ];
            $scope.photos=[
                {img:'2-13',text:"欧颂庄园红葡萄酒"},
                {img:'2-14',text:"圣彼得堡葡萄酒"},
                {img:'2-15',text:"圣彼得堡葡萄酒"},
                {img:'2-16',text:"圣彼得堡葡萄酒"},
                {img:'2-17',text:"圣彼得堡葡萄酒"},
                {img:'2-18',text:"圣皮尔古堡干白葡萄酒"},
                {img:'2-19',text:"圣皮尔古堡干红葡萄酒"},
                {img:'2-20',text:"首席法兰西香槟特酿"},
                {img:'2-21',text:"洋酒百加得白朗姆酒"},
                {img:'2-22',text:"卓林普乐怡诺红葡萄酒"}
            ];
            $scope.btn=0;
        }
])
// 第三个页面
    App.controller('three',['$scope',
        function($scope){
            $scope.arr=[
                {text:"啤酒企业也防添加剂 下半年或临涨价潮",date:"2017-05-03"},
                {text:"深圳将建华南最大葡萄酒交易中心",date:"2017-05-03"},
                {text:"投资缺乏热点名酒受到追捧 陈年茅台遇“爆冷”",date:"2017-05-03"},
                {text:"国务院食品安全委员会将加强酒类质量监管",date:"2017-05-03"},
                {text:"帝亚吉欧控股水井坊获放行",date:"2017-05-03"},
                {text:"万吨酱酒基地为湘酒发力",date:"2017-05-03"},
                {text:"外资'酿'白酒",date:'2017-05-03'},
                {text:"预计2014年中国葡萄酒销量达60亿美元",date:"2017-05-03"},
                {text:"一线白酒价格涨势出现加速迹象",date:"2017-05-03"},
                {text:"2010年中国啤酒行业利税总额排行榜发布",date:"2017-05-03"},
                {text:"朝日啤酒出价1亿美元收购新西兰果汁商",date:"2017-05-03"},
                {text:"葡萄酒B2C模式进入如火如荼发展阶段",date:"2017-05-03"},
                {text:"我国白酒业现状：六成企业规模偏小 产业集中度较低",date:"2017-05-03"},
                {text:"'拉菲传奇'都是传说 浙江捉大量红酒'李鬼'",date:"2017-05-03"},
            ]
    }])
// 第四个页面
    App.controller('four',['$scope','$http','$window',
        function($scope,$http,$window){
            $scope.reloadRoute=function(){
                $window.location.reload();
            };
            $scope.arr=[];
            $http.get('php/alcohol.php',{
                params:{
                    act:'list'
                }
            }).success(function(data){
                $scope.arr=data;
            }).error(function(){
                alert("数据读取失败！(注:请不要快速刷新页面)");
            });
            $scope.tet=function(id){
                if($scope.name==''||$scope.name==undefined){
                    alert("姓名不能为空");
                }else if($scope.mailbox==''||$scope.mailbox==undefined){
                    alert("邮箱不能为空");
                }else if($scope.phone==''||$scope.phone==undefined){
                    alert("电话不能为空");
                }else if($scope.content==''||$scope.content==undefined){
                    alert("留言不能为空");
                }else if(isNaN($scope.phone)||$scope.phone==undefined){
                    alert("电话不能为空且必须为数字");
                }else{
                    $http.get('php/alcohol.php',{
                        params:{
                            act:'add',
                            name:$scope.name,
                            mailbox:$scope.mailbox,
                            phone:$scope.phone,
                            content:$scope.content,
                        }
                    }).success(function(){
                        alert("留言成功");
                        $scope.reloadRoute();
                    }).error(function(){
                        alert("留言失败");
                    });
                }
            }
            $scope.delete=function(id){
                $http.get('php/alcohol.php',{
                    params:{
                        act:'del',
                        id:id
                    }
                }).success(function(){
                    alert("删除成功");
                    $scope.reloadRoute();
                }).error(function(){
                    alert("删除失败");
                })
            }
        }
    ]);
//登录注册页
    App.controller('login',['$scope','$http','$window','$location',
        function($scope,$http,$window,$location){
            $scope.login=0;
        $scope.reloadRoute=function(){
            $window.location.reload();
        };
        $scope.loginClick=function(){
            if($scope.name1==''||$scope.name1==undefined){
                alert("姓名不能为空");
            }else if($scope.password1==''||$scope.password1==undefined){
                alert("密码不能为空");              
            }else if($scope.name1=='one'&&$scope.password1=="123"){
                alert("登录成功");
                $scope.reloadRoute();
                $location.path("/nav1");
            }else{
                alert("登录失败");
                $scope.reloadRoute();
                alert("用户名为：one，密码为:123")
            }
         }
        $scope.register=function(id){
            if($scope.name==''||$scope.name==undefined){
                alert("注册时姓名不能为空");
            }else if($scope.password==''||$scope.password==undefined){
                alert("注册时密码不能为空");              
            }else{
            $http.get('php/login.php',{
                params:{
                    act:'add',
                    name:$scope.name,
                    password:$scope.password,
                    }
            }).success(function(){
                alert("注册成功");
                $scope.reloadRoute();
            }).error(function(){
                alert("注册失败")
            })
            }
        }              
        }
    ])